apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccount: nsse-sa-prod
      volumes:
      - name: tls
        secret:
          secretName: tls
      imagePullSecrets:
      - name: ecr
      containers:
      - name: order
        image: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/order
        ports:
        - containerPort: 4443
        envFrom:
        - configMapRef:
            name: config-map
        volumeMounts:
        - name: tls
          readOnly: true
          mountPath: /nsse-backend/certificates
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /order/health
            port: 4443
            scheme: HTTPS
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 120
          timeoutSeconds: 15
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /order/health
            port: 4443
            scheme: HTTPS
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 3
          timeoutSeconds: 15
          periodSeconds: 3
        securityContext:
          allowPrivilegeEscalation: false
