apiVersion: v1
kind: Service
metadata:
  name: order
  annotations:
    service.kubernetes.io/topology-mode: Auto
    alb.ingress.kubernetes.io/healthcheck-path: /order/health
spec:
  type: NodePort
  selector:
    app: order
  ports:
  - port: 4443
    nodePort: 30000