apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.orderDeployment.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.orderDeployment.autoScaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.orderDeployment.autoScaling.averageCpuUtilization }}
  behavior:
    scaleDown:
      {{- toYaml .Values.orderDeployment.autoScaling.scaleDown | nindent 6 }}
    scaleUp:
      {{- toYaml .Values.orderDeployment.autoScaling.scaleUp | nindent 6 }}