namespace: nsse
nameSuffix: "-prod"
namePrefix: "nsse-"
commonLabels:
  application: not-so-simple-ecommerce
resources: 
  - namespace.yml
  - image-pull-secret.yml
  - config-map.yml
  - order/deployment.yml
images:
  - name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/order
    newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/order
    newTag: latest