namespace: nsse
nameSuffix: "-prod"
namePrefix: "nsse-"
commonLabels:
  application: not-so-simple-ecommerce
resources: 
  - application/namespace.yml
  - application/config-map.yml
  - application/service-account.yml
  - application/secrets/ecr-image-pull-credentials.yml
  - application/secrets/kestrel-certificate.yml
  - application/secrets/mongo-certificate.yml
  # application/- health-checker/deployment.yml
  - application/identity-server/deployment.yml
  - application/invoice-generator/deployment.yml
  - application/main/deployment.yml
  - application/notificator/deployment.yml
  - application/order/deployment.yml
  # application/- health-checker/service.yml
  - application/identity-server/service.yml
  - application/invoice-generator/service.yml
  - application/main/service.yml
  - application/notificator/service.yml
  - application/order/service.yml
  - application/identity-server/hpa.yml
  - application/invoice-generator/hpa.yml
  - application/main/hpa.yml
  - application/notificator/hpa.yml
  - application/order/hpa.yml
  - application/ingress.yml
  - infrastructure/network-policies/ingress.yml
  - infrastructure/network-policies/egress.yml
images:
  - name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/order
    newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/order
    newTag: latest

  - name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/main
    newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/main
    newTag: latest

  - name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/identity-server
    newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/identity-server
    newTag: latest

  - name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/notificator
    newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/notificator
    newTag: latest

  - name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/health-checker
    newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/health-checker
    newTag: latest

  - name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/invoice-generator
    newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/invoice-generator
    newTag: latest