namespace: nsse
nameSuffix: "-prod"
namePrefix: "nsse-"
commonLabels:
  application: not-so-simple-ecommerce
resources: 
  - infrastructure/namespace.yml
  - infrastructure/config-map.yml
  - infrastructure/service-account.yml
  - infrastructure/secrets/ecr-image-pull-credentials.yml
  - infrastructure/secrets/kestrel-certificate.yml
  - infrastructure/secrets/mongo-certificate.yml
  - infrastructure/ingress.yml
  - infrastructure/network-policies/ingress.yml
  - infrastructure/network-policies/egress.yml

helmGlobals:
  chartHome: application

helmCharts:
- name: health-checker
  repo: health-checker
  releaseName: health-checker
  valuesFile: application/health-checker/values.yaml

- name: identity-server
  repo: identity-server
  releaseName: identity-server
  valuesFile: application/identity-server/values.yaml

- name: invoice-generator
  repo: invoice-generator
  releaseName: invoice-generator
  valuesFile: application/invoice-generator/values.yaml

- name: main
  repo: main
  releaseName: main
  valuesFile: application/main/values.yaml

- name: notificator
  repo: notificator
  releaseName: notificator
  valuesFile: application/notificator/values.yaml

- name: order
  repo: order
  releaseName: order
  valuesFile: application/order/values.yaml

images:
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/order
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/order
    newTag: latest

  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/main
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/main
    newTag: latest

  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/identity-server
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/identity-server
    newTag: latest

  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/notificator
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/notificator
    newTag: latest

  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/health-checker
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/health-checker
    newTag: latest

  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/invoice-generator
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/invoice-generator
    newTag: latest