apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-server
  template:
    metadata:
      labels:
        app: identity-server
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: identity-server
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccount: nsse-sa-prod
      volumes:
      - name: kestrel
        secret:
          secretName: kestrel-certificate
      imagePullSecrets:
      - name: ecr-image-pull-credentials
      containers:
      - name: identity-server
        image: 968225077300.dkr.ecr.us-east-1.amazonaws.com/nsse/production/identity-server
        ports:
        - containerPort: 4443
        envFrom:
        - configMapRef:
            name: config-map
        volumeMounts:
        - name: kestrel
          readOnly: true
          mountPath: /nsse-backend/certificates/kestrel
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /invoice/health
            port: 4443
            scheme: HTTPS
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 120
          timeoutSeconds: 15
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /invoice/health
            port: 4443
            scheme: HTTPS
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 3
          timeoutSeconds: 15
          periodSeconds: 3