apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    service.kubernetes.io/topology-mode: Auto
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.invoiceGeneratorDeployment.livenessProbe.httpGet.path }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.invoiceGeneratorDeployment.containerPort }}
    nodePort: {{ .Values.invoiceGeneratorDeployment.nodePort }}