apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.mainDeployment.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      application: not-so-simple-ecommerce
  strategy:
    blueGreen:
      activeService: {{ .Values.mainDeployment.activeServiceName }}
      previewService: {{ .Values.mainDeployment.previewServiceName }}
      autoPromotionEnabled: {{ .Values.mainDeployment.blueGreen.autoPromotionEnabled }}
      scaleDownDelaySeconds: 300
      abortScaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: nsse-health-check-prod
        args:
        - name: url
          value: https://{{ .Values.mainDeployment.previewServiceName }}.nsse.svc.cluster.local:{{ .Values.mainDeployment.containerPort }}/main/health
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        application: not-so-simple-ecommerce
    spec:
      topologySpreadConstraints:
      {{- range .Values.mainDeployment.topologySpreadConstraints }}
      - maxSkew: {{ .maxSkew }}
        topologyKey: {{ .topologyKey }}
        whenUnsatisfiable: {{ .whenUnsatisfiable }}
        labelSelector:
          matchLabels:
            app: {{ $.Release.Name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.mainDeployment.securityContext | nindent 8 }}
      serviceAccount: {{ .Values.mainDeployment.serviceAccount }}
      volumes:
        {{- toYaml .Values.mainDeployment.volumes | nindent 6 }}
      imagePullSecrets:
      - name: {{ .Values.mainDeployment.imagePullSecrets }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.mainDeployment.image }}
        ports:
        - containerPort: {{ .Values.mainDeployment.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.mainDeployment.configMap }}
        volumeMounts:
          {{- toYaml .Values.mainDeployment.volumeMounts | nindent 8 }}
        resources:
          {{- toYaml .Values.mainDeployment.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.mainDeployment.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.mainDeployment.readinessProbe | nindent 10 }}
