mainDeployment:
  image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nsse/production/main
  containerPort: 4443
  nodePort: 30002
  configMap: nsse-config-map-prod
  replicaCount: 1
  serviceAccount: nsse-sa-prod
  imagePullSecrets: nsse-ecr-image-pull-credentials-prod
  autoScaling:
    minReplicas: 1
    maxReplicas: 3
    averageCpuUtilization: 50
    scaleDown:  
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        value: 2
        periodSeconds: 15
      - type: Percent
        value: 50
        periodSeconds: 15
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  volumes:
  - name: kestrel
    secret:
      secretName: kestrel-certificate
  - name: mongo
    secret:
      secretName: mongo-certificate
  volumeMounts: 
  - name: kestrel
    readOnly: true
    mountPath: /nsse-backend/certificates/kestrel
  - name: mongo
    readOnly: true
    mountPath: /nsse-backend/certificates/mongo
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  livenessProbe:
    httpGet:
      path: /main/health
      port: 4443
      scheme: HTTPS
    successThreshold: 1
    failureThreshold: 3
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 60
  readinessProbe:
    httpGet:
      path: /main/health
      port: 4443
      scheme: HTTPS
    successThreshold: 1
    failureThreshold: 3
    initialDelaySeconds: 3
    timeoutSeconds: 15
    periodSeconds: 3